// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/history": {
    params: {};
  };
  "/settings": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/history" | "/settings";
  };
  "./layouts/navbar-layout.jsx": {
    id: "layouts/navbar-layout";
    page: "/" | "/history" | "/settings";
  };
  "pages/HomePage.jsx": {
    id: "pages/HomePage";
    page: "/";
  };
  "pages/HistoryPage.jsx": {
    id: "pages/HistoryPage";
    page: "/history";
  };
  "pages/SettingsPage.jsx": {
    id: "pages/SettingsPage";
    page: "/settings";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "layouts/navbar-layout": typeof import("./app/./layouts/navbar-layout.jsx");
  "pages/HomePage": typeof import("./app/pages/HomePage.jsx");
  "pages/HistoryPage": typeof import("./app/pages/HistoryPage.jsx");
  "pages/SettingsPage": typeof import("./app/pages/SettingsPage.jsx");
};